spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  config:
    activate:
      on-profile: native

server:
  port: 8071